### ISSUE TITLE
Clarify Atlas is optional

### ISSUE THREAD

**Issue by jamesdaniels** [hashicorp/best-practices#213]
Right now if you follow the instructions given on this page https://github.com/hashicorp/best-practices/blob/master/terraform/providers/aws/README.md it can end up being very expensive.

These docs should be reworked to clarify Atlas is optional, per #94

**Comment by mitchellh** [comment]
I agree with this. I'll poke around to see what I can get done here. :)

**Comment by jamesdaniels** [comment]
Thanks

**Comment by missinglink** [comment]
Hi, any update on this issue?

**Comment by bensojona** [comment]
@missinglink fixed in https://github.com/hashicorp/best-practices/pull/222
