### ISSUE TITLE
Plan results in multiple missing Vars

### ISSUE THREAD

**Issue by cmacmurray** [hashicorp/best-practices#214]
Terraform v0.8.2

Setting up remote state...
Downloading remote modules...
Refreshing Terraform state prior to plan...
There are warnings and/or errors related to your configuration. Please
fix these before continuing.

[31mErrors:
[0m[0m
[31m  * 45 error(s) occurred:

* Required variable not set: site_private_key
* Required variable not set: consul_node_count
* Required variable not set: vault_node_count
* Required variable not set: vault_instance_type
* Required variable not set: vault_artifacts
* Required variable not set: nodejs_artifact_name
* Required variable not set: atlas_token
* Required variable not set: vault_ssl_cert
* Required variable not set: private_subnets
* Required variable not set: openvpn_instance_type
* Required variable not set: nodejs_artifacts
* Required variable not set: bastion_instance_type
* Required variable not set: openvpn_cidr
* Required variable not set: vault_artifact_name
* Required variable not set: haproxy_artifact_name
* Required variable not set: name
* Required variable not set: sub_domain
* Required variable not set: atlas_username
* Required variable not set: azs
* Required variable not set: haproxy_artifacts
* Required variable not set: nodejs_blue_node_count
* Required variable not set: nodejs_green_instance_type
* Required variable not set: openvpn_ami
* Required variable not set: consul_artifacts
* Required variable not set: artifact_type
* Required variable not set: region
* Required variable not set: atlas_aws_global
* Required variable not set: vpc_cidr
* Required variable not set: site_public_key
* Required variable not set: vault_ssl_key
* Required variable not set: nodejs_blue_instance_type
* Required variable not set: nodejs_green_weight
* Required variable not set: public_subnets
* Required variable not set: consul_artifact_name
* Required variable not set: haproxy_instance_type
* Required variable not set: nodejs_blue_weight
* Required variable not set: site_ssl_key
* Required variable not set: openvpn_admin_pw
* Required variable not set: consul_instance_type
* Required variable not set: haproxy_node_count
* Required variable not set: nodejs_green_node_count
* Required variable not set: atlas_environment
* Required variable not set: site_ssl_cert
* Required variable not set: openvpn_user
* Required variable not set: openvpn_admin_user[0m[0m

Setup failed: failed refreshing state (exit 1)

**Comment by bensojona** [comment]
This is due to these Terraform variables not being set in Terraform Enterprise. 

You can resolve this by either manually setting them in your TFE environment, or using the `terraform push` command as noted in the [terraform push step](https://github.com/hashicorp/best-practices/tree/master/terraform/providers/aws#provision-the-aws-us-east-1-prod-environment) of the environment you're standing up.
