### ISSUE TITLE
Teardown (destroy) guide would be useful addition.

### ISSUE THREAD

**Issue by akramhussein** [hashicorp/best-practices#22]
Thanks for putting this together. I followed the guide and other than a few hiccups it was a good tutorial to follow.

As the set up is non-trivial, I found that tearing it down with terraform destroy was not straightforward.
It would be great to have a section to describe how to do this.

**Comment by bensojona** [comment]
Great suggestion. There are a few Terraform bugs preventing make this a single command destroy. I'll update with the destroy hiccups.

Would you mind sharing hiccups you came across? I'd like to either fix them, or document it better. Thanks!

**Comment by akramhussein** [comment]
Sounds good!

Some things I ran in to:

- Wasn't completely obvious to me, but I kind of expected the Terraform Configuration Github Integration to also pull in the Terraform Variables and I was only expected to update them.

I think the way I read the [aws-global set up](https://github.com/hashicorp/best-practices/blob/master/terraform/providers/aws/README.md#provision-the-aws-global-environment) led me to think this was the case. So I spent some time re-importing thinking it was a mistake.
Anyways, it wasn't, although that would be a nice enhancement.

- In setting up the Packer builds, wasn't obvious that the name of the build had to be identical configuration name. I haphazardly typed in 'test' for the first one and couldn't work out why it wasn't working.

- I was never able to get the Node.js app running. 2 instances would spin up and then terminate and 'Apply' would fail between those stages saying auto-scaling would not work.

All I can recall for now. I think most were my mis-understsanding of how a particular service worked.

Apologies if these aren't clear or useful.

**Comment by bensojona** [comment]
@akramhussein great feedback! I've [updated the README](https://github.com/hashicorp/best-practices/pull/34). Let me know if I've missed anything or if you have any other suggestions for updates to make for a better experience.

- Added `terraform destroy` docs.
  - Could you send me any errors you were getting during the destroy? Want to make sure I have all of those covered...
- The GitHub Ingress should pull in variables, but at the moment does not. This is something that will be added to Atlas soon. For now, I've updated the docs with a necessary `terraform push` step that was missing.
- Updated the README to better point out what the name should be when using the [Create New Build Configuration](https://atlas.hashicorp.com/builds/new) tool.
- Could you send me the failed apply output for the Node.js app issue? Happy to help troubleshoot this.

**Comment by akramhussein** [comment]
@bensojona Unfortunately I don't have the logs anymore, I destroyed the set up, to start preparing a real one.

From memory:

* `terraform destroy` would say "can't find IAM". A Google search led me to try `terraform get` and then `terraform destroy` in the global folder. That somewhat worked but didn't work for the staging config. I never thought to use the Atlas var's via the CLI, but it never told me to do anything as such and to my memory it was in the shell's environment.

* Node.js `terraform apply` error was something like:

"There was an error...autoscaling failed...this may be because some instances failed to start..."

* Consule Node.js service error showed:

"Get http://localhost:8888: dial tcp 127.0.0.1:8888: getsockopt: connection refused"

After a while the 2 instances would terminate.

I'm no longer working with the best practice environment per se (destroyed it) as I'm now trying to build a real env but thank you for offering. Let me know if I can be of any more help.

**Comment by bensojona** [comment]
@akramhussein thanks, much appreciated!
